"""Runtime matcher for dynamic custom gestures.

`DynamicGestureClassifier` consumes a stream of frame-by-frame
normalized hand landmarks and fires a `Match` when the user's recent
motion resembles one of the registered gestures.

Two-stage detection so we don't run DTW on every frame:

  1. **Motion gate**. A short trailing window's path length is
     compared to a low/high threshold pair. When energy crosses
     LOW→HIGH we mark a "gesture in progress"; when it crosses
     HIGH→LOW (the user settled) we close out the segment and run
     stage 2 on it.
  2. **DTW match**. The closed segment's key-point trajectories are
     resampled to the canonical 32 frames and compared against every
     stored sample trajectory of every gesture using Sakoe-Chiba-banded
     DTW. The lowest distance is the winning match — fires only if
     it's also below `match_threshold`.

Cooldowns are external to this class (the existing custom-gesture
runner handles per-gesture cooldowns the same way it does for the
static matcher), so a match can be returned every closed segment.
"""
from __future__ import annotations

from collections import deque
from dataclasses import dataclass, field
from typing import Deque, List, Optional, Sequence, Tuple

import numpy as np

from .dynamic_recording import (
    NUM_LANDMARKS,
    RESAMPLED_FRAME_COUNT,
    _resample_landmarks,
    _resample_wrist,
)


# ---------------------------------------------------------------------------
# Tunables. Tied to the normalized coordinate system (wrist at origin,
# palm scale = 1). Numbers below come from running the recordings
# generated by tests/test_dynamic_gesture_key_points.py through the
# classifier in dev — synthetic but representative.

# Frames retained in the sliding window. At 30 fps that's ~3.3 seconds,
# enough to capture any gesture the user could plausibly perform.
_WINDOW_FRAMES = 100

# Trailing window length used to compute motion energy. Short enough
# to be responsive (so the gate flips within ~150 ms of the user
# starting or stopping), long enough to smooth single-frame jitter.
_MOTION_WINDOW_FRAMES = 5

# Energy gate thresholds in normalized-coords-per-frame. Measured
# as the average over the trailing window of the per-frame MAX
# landmark motion (i.e. the fastest-moving landmark on each frame).
# Using max — not mean — is important: a one-finger swipe only moves
# ~3 of 21 landmarks, so a mean would be dominated by the 18 static
# landmarks and miss the gesture entirely.
#
# Reference numbers (synthetic + real MediaPipe testing at 30 fps):
#   * still hand + MediaPipe jitter: per-frame max ~0.008-0.015
#   * one-finger swipe at moderate speed: per-frame max ~0.030-0.050
#   * fast clap: per-frame max ~0.060-0.120
# Hysteresis gap (LOW < HIGH) prevents bouncing between states on
# borderline motion. Gates are tuned so a normal still hand reliably
# falls below LOW and a deliberate gesture clears HIGH within
# 2-3 frames.
_MOTION_GATE_LOW = 0.018    # below this → "settled"
_MOTION_GATE_HIGH = 0.030   # above this → "in progress"

# r45 (opt-in fps-invariant path — HGR_DYNAMIC_FPS_INVARIANT=1).
# The original gates above are calibrated per-FRAME at 30 fps. At
# 15 fps a still hand's jitter per-frame doubles and can trip HIGH;
# at 60 fps the per-frame step halves and slow deliberate gestures
# never clear it. When the env flag is ON we swap in per-SECOND
# equivalents and divide each per-frame step by real dt so gating
# becomes fps-invariant. DEFAULT OFF preserves existing behaviour
# for all users on all fps (per backward-compat critique — off-30-fps
# users have templates calibrated to the old per-frame semantics).
_MOTION_GATE_LOW_PER_SEC = _MOTION_GATE_LOW * 30.0   # ≈ 0.54
_MOTION_GATE_HIGH_PER_SEC = _MOTION_GATE_HIGH * 30.0  # ≈ 0.90
_NOMINAL_FRAME_DT = 1.0 / 30.0
# Duration floor for the fps-invariant close-out: 8 frames @ 30 fps ≈
# 0.267 s. Only consulted when the env flag is ON.
_MIN_SEGMENT_DURATION_S = 0.25

# Minimum number of "in progress" frames before we accept a segment.
# Filters out tiny twitches that briefly cross the high gate.
_MIN_SEGMENT_FRAMES = 8

# DTW band radius (Sakoe-Chiba). 8 frames of slack on a 32-frame
# template handles speed variations up to ±25% from the recorded
# template. Tighter = faster + stricter timing; looser = more
# forgiving but slower.
_DTW_BAND = 8

# Default match threshold. Average per-frame Euclidean distance
# (across key-point feature vectors) below this is considered a
# match. Tightened from 0.30 → 0.18 after real-hand testing showed
# the looser threshold matched almost any open-hand motion.
_DEFAULT_MATCH_THRESHOLD = 0.18

# Reference wrist path length (palm units) used to map a template's
# per-take wrist motion into a [0, 1] strength weight. A take whose
# wrist travels this many palm units in total is treated as "fully
# wrist-driven" (weight clamps near MAX). A take whose wrist barely
# moves yields weight ≈ 0 — the wrist channel then contributes
# nothing and the classifier matches on fingers alone. Tuned so a
# moderate swipe (~1.5 palm units of total path) lands near 1.0.
_WRIST_MOTION_REFERENCE_PALM_UNITS = 1.5

# Cap on the wrist-channel weight so finger features always retain
# at least 1 - MAX influence on the combined distance. Stops a big
# swipe template from matching ANY fast hand path regardless of
# finger pose. 0.7 = wrist dominates (70%) for big-motion templates
# but fingers still keep 30% weight.
_WRIST_WEIGHT_MAX = 0.7


@dataclass(frozen=True)
class DynamicGestureTemplate:
    """A registered gesture the classifier knows how to match.

    `sample_trajectories` is a list of N (one per recorded take) of
    shape (resampled_length, num_key_points, 3). Each is the take's
    key-point trajectory after key-point selection has dropped the
    static / inconsistent landmarks. Storing all N takes (rather than
    just a centroid) lets DTW match against the variant the user is
    most closely reproducing on the current attempt.

    `wrist_trajectories` is a parallel list of N (resampled_length, 3)
    arrays — the absolute (palm-scaled) wrist position per frame for
    each take. This is the second DTW channel: DTW on the finger
    features alone can't distinguish a swipe from "hand entered view
    and held still" (both look like a stationary wrist-relative hand),
    so we also DTW the wrist path and combine the distances weighted
    by how much wrist motion the template's takes actually contained.
    `wrist_motion_strength` is computed at build time in [0, 1] from
    the takes' wrist path lengths and capped at _WRIST_WEIGHT_MAX so
    finger features always retain some influence.
    """

    name: str
    key_point_indices: List[int]
    sample_trajectories: List[np.ndarray]
    wrist_trajectories: List[np.ndarray] = field(default_factory=list)
    wrist_motion_strength: float = 0.0
    # Optional per-gesture threshold. None → use classifier default.
    match_threshold: Optional[float] = None


@dataclass(frozen=True)
class Match:
    """Result of a successful classification."""

    gesture_name: str
    distance: float
    matched_sample_index: int      # which of the gesture's N takes was closest
    segment_frame_count: int
    timestamp: float


class DynamicGestureClassifier:
    def __init__(
        self,
        templates: Sequence[DynamicGestureTemplate],
        *,
        match_threshold: float = _DEFAULT_MATCH_THRESHOLD,
        window_frames: int = _WINDOW_FRAMES,
        motion_gate_low: float = _MOTION_GATE_LOW,
        motion_gate_high: float = _MOTION_GATE_HIGH,
        min_segment_frames: int = _MIN_SEGMENT_FRAMES,
        dtw_band: int = _DTW_BAND,
    ) -> None:
        self._templates: List[DynamicGestureTemplate] = list(templates)
        self._match_threshold = float(match_threshold)
        # r45: HGR_DYNAMIC_FPS_INVARIANT=1 opts in to per-second gates.
        # DEFAULT OFF — the constructor arg semantics (per-frame) are
        # preserved byte-for-byte for every existing caller.
        try:
            import os as _os
            self._fps_invariant = _os.environ.get("HGR_DYNAMIC_FPS_INVARIANT", "0") == "1"
        except Exception:
            self._fps_invariant = False
        if self._fps_invariant:
            # Scale the per-frame constructor arg to a per-second gate
            # using the 30-fps identity — a caller passing the default
            # 0.018/0.030 pair gets 0.54/0.90 per-second gates so 30-fps
            # trip points are byte-identical.
            self._motion_gate_low = float(motion_gate_low) / _NOMINAL_FRAME_DT
            self._motion_gate_high = float(motion_gate_high) / _NOMINAL_FRAME_DT
        else:
            self._motion_gate_low = float(motion_gate_low)
            self._motion_gate_high = float(motion_gate_high)
        self._min_segment_frames = int(min_segment_frames)
        self._dtw_band = int(dtw_band)
        # Each entry: (timestamp, normalized_landmarks, wrist_palm_scaled_or_None).
        # The wrist-position third element is optional so the existing
        # 2-arg `update(...)` callers continue to work.
        self._frames: Deque[Tuple[float, np.ndarray, Optional[np.ndarray]]] = deque(
            maxlen=int(window_frames)
        )
        # Motion-gate state machine.
        self._in_progress = False
        self._segment_start_idx: Optional[int] = None
        # Bookkeeping for tests / diagnostics.
        self._last_segment_motion = 0.0

    @property
    def in_progress(self) -> bool:
        """True while motion is above the high gate. Useful for UI."""
        return self._in_progress

    def reset(self) -> None:
        """Drop the sliding window. Call when entering a state where
        recent motion is irrelevant (e.g. mode switch, dialog open)."""
        self._frames.clear()
        self._in_progress = False
        self._segment_start_idx = None

    def update(
        self,
        landmarks_normalized: np.ndarray,
        timestamp: float,
        *,
        wrist_palm_scaled: Optional[np.ndarray] = None,
    ) -> Optional[Match]:
        """Append one normalized-landmark frame.

        `landmarks_normalized` shape (21, 3) — wrist-relative, palm-
        scaled. Returns a Match when a gesture segment just closed
        AND matched a template; None otherwise.

        `wrist_palm_scaled` is the OPTIONAL absolute wrist position
        in palm units (raw_wrist / palm_scale). When provided, the
        classifier uses it to gate out segments where the wrist
        barely moved — the wrist-relative normalization above
        otherwise can't distinguish a real swipe (whole hand
        translates) from "user brought their hand into view and
        held it steady" (wrist also moves but wrist-relative
        landmarks look identical).
        """
        if landmarks_normalized.shape != (NUM_LANDMARKS, 3):
            raise ValueError(
                f"expected (21, 3); got {landmarks_normalized.shape}"
            )
        wrist_entry: Optional[np.ndarray] = None
        if wrist_palm_scaled is not None:
            wrist_entry = np.asarray(wrist_palm_scaled, dtype=np.float32).reshape(-1)
        self._frames.append(
            (float(timestamp), landmarks_normalized.astype(np.float32), wrist_entry)
        )

        # Compute motion energy over the trailing window.
        motion = self._recent_motion_energy()

        if not self._in_progress:
            if motion >= self._motion_gate_high:
                self._in_progress = True
                # Start the segment a few frames BACK so the captured
                # motion includes the user's lead-in (not just the
                # frame the gate happened to trip on).
                lookback = min(_MOTION_WINDOW_FRAMES, len(self._frames))
                self._segment_start_idx = len(self._frames) - lookback
            return None

        # Currently in progress — wait for motion to settle.
        if motion <= self._motion_gate_low:
            # Close the segment and try to match.
            return self._close_and_match(timestamp)
        return None

    # ---- internal ----

    def _recent_motion_energy(self) -> float:
        """Per-frame motion magnitude, averaged over the trailing window.

        Two channels considered, MAX taken:
          * Wrist-relative landmark MAX — the fastest-moving landmark
            in palm-scaled wrist-subtracted space. Captures finger
            motion (curl, spread, wiggle, fist squeeze).
          * Absolute wrist step — the wrist's own palm-scaled
            displacement. Captures whole-hand translation (swipe,
            wave) that wrist-relative landmarks erase.

        Taking MAX means EITHER channel can open the gate, so a rigid-
        hand swipe (still fingers + moving wrist) trips it just as
        readily as an in-place fist squeeze (moving fingers + still
        wrist). Using max-across-landmarks (not mean) for the relative
        channel preserves single-finger gestures the same way; the
        wrist channel is single-valued so it's just the step norm.

        Pre-wrist-channel callers (no wrist data in the deque) fall
        back to the relative channel only — same behaviour as before.
        """
        if len(self._frames) < 2:
            return 0.0
        window = list(self._frames)[-_MOTION_WINDOW_FRAMES:]
        if len(window) < 2:
            return 0.0
        total = 0.0
        for prev, current in zip(window[:-1], window[1:]):
            diff = current[1] - prev[1]  # (21, 3) wrist-relative
            step_norms = np.linalg.norm(diff, axis=-1)  # (21,)
            finger_max = float(step_norms.max())
            wrist_step = 0.0
            prev_wrist = prev[2]
            curr_wrist = current[2]
            if prev_wrist is not None and curr_wrist is not None:
                wrist_step = float(np.linalg.norm(curr_wrist - prev_wrist))
            step = max(finger_max, wrist_step)
            # r45: scale by real dt WHEN the fps-invariant flag is on so
            # the summed energy is displacement/second; otherwise emit
            # per-frame displacement exactly as before. Guarded against
            # zero/negative dt (falls back to nominal 30-fps step).
            if self._fps_invariant:
                dt = float(current[0]) - float(prev[0])
                if not (dt > 1e-6):
                    dt = _NOMINAL_FRAME_DT
                total += step / dt
            else:
                total += step
        return total / max(1, (len(window) - 1))

    def _segment_wrist_resampled(
        self,
        segment: List[Tuple[float, np.ndarray, Optional[np.ndarray]]],
    ) -> Optional[np.ndarray]:
        """Resample the segment's absolute wrist trajectory to the
        canonical length. Returns None when the caller didn't supply
        wrist data (older 2-arg `update()` callers).
        """
        wrists = [w for _, _, w in segment if w is not None]
        if len(wrists) < 2:
            return None
        stacked = np.stack(wrists, axis=0).astype(np.float32)
        try:
            return _resample_wrist(stacked, RESAMPLED_FRAME_COUNT)
        except Exception:
            return None

    def _close_and_match(self, timestamp: float) -> Optional[Match]:
        if self._segment_start_idx is None:
            self._in_progress = False
            return None
        all_frames = list(self._frames)
        segment = all_frames[self._segment_start_idx:]
        self._in_progress = False
        self._segment_start_idx = None
        if len(segment) < self._min_segment_frames:
            return None

        landmarks_stack = np.stack([lm for _, lm, _ in segment], axis=0).astype(np.float32)
        self._last_segment_motion = float(landmarks_stack.std())

        # Resample the segment's wrist trajectory once (used across
        # every template that carries a wrist channel). None when the
        # caller didn't pass wrist data — older 2-arg update() shape,
        # in which case we silently fall back to finger-only matching.
        seg_wrist_resampled = self._segment_wrist_resampled(segment)

        best: Optional[Match] = None
        for template in self._templates:
            if not template.sample_trajectories:
                continue
            try:
                key_indices = template.key_point_indices
                # Extract the segment's key-point trajectory only.
                segment_kp = landmarks_stack[:, key_indices, :]
                # Resample to the canonical length so DTW comparison
                # is bounded.
                resampled = _resample_landmarks(segment_kp, RESAMPLED_FRAME_COUNT)
                # Flatten the per-frame key-point xyz into one feature
                # vector per frame so DTW operates on (frames × F).
                seg_features = resampled.reshape(RESAMPLED_FRAME_COUNT, -1)
            except Exception:
                continue
            threshold = (
                template.match_threshold
                if template.match_threshold is not None
                else self._match_threshold
            )
            # Weight for the wrist channel. Falls to 0 (finger-only)
            # whenever the template carries no wrist data (e.g. legacy
            # records loaded from registry without wrist_trajectories)
            # OR the live caller didn't supply wrist positions.
            template_wrist = template.wrist_trajectories or []
            wrist_weight = 0.0
            if (
                seg_wrist_resampled is not None
                and len(template_wrist) == len(template.sample_trajectories)
                and template.wrist_motion_strength > 0.0
            ):
                wrist_weight = float(template.wrist_motion_strength)
            wrist_weight = max(0.0, min(_WRIST_WEIGHT_MAX, wrist_weight))
            finger_weight = 1.0 - wrist_weight
            for sample_idx, sample in enumerate(template.sample_trajectories):
                try:
                    sample_features = sample.reshape(sample.shape[0], -1)
                except Exception:
                    continue
                if sample_features.shape[1] != seg_features.shape[1]:
                    # Schema mismatch (different key-point count).
                    continue
                finger_dist = _dtw_distance(seg_features, sample_features, band=self._dtw_band)
                if wrist_weight > 0.0 and sample_idx < len(template_wrist):
                    wrist_sample = template_wrist[sample_idx]
                    try:
                        wrist_dist = _dtw_distance(
                            seg_wrist_resampled, wrist_sample.astype(np.float32),
                            band=self._dtw_band,
                        )
                    except Exception:
                        wrist_dist = finger_dist  # neutral on failure
                else:
                    wrist_dist = 0.0
                distance = finger_weight * finger_dist + wrist_weight * wrist_dist
                if distance < threshold and (best is None or distance < best.distance):
                    best = Match(
                        gesture_name=template.name,
                        distance=float(distance),
                        matched_sample_index=int(sample_idx),
                        segment_frame_count=int(len(segment)),
                        timestamp=float(timestamp),
                    )
        return best


# ---------------------------------------------------------------------------
# DTW

def _dtw_distance(a: np.ndarray, b: np.ndarray, *, band: int = _DTW_BAND) -> float:
    """Sakoe-Chiba-banded DTW returning a length-normalized cost.

    `a`, `b` are (T_a, F) and (T_b, F). Cost is the optimal warped
    cumulative L2 distance between paired frames divided by the
    sum of lengths — this normalizes for the two sequences being
    different lengths so the resulting number is comparable across
    different segments.

    The band constrains the warping path to |i - j| <= band, which
    is enough for ±25% speed differences on a 32-frame template
    and cuts the complexity from O(T_a × T_b) to O(T × band).
    """
    if a.shape[1] != b.shape[1]:
        raise ValueError(f"feature dim mismatch: {a.shape[1]} vs {b.shape[1]}")
    ta, tb = a.shape[0], b.shape[0]
    if ta == 0 or tb == 0:
        return float("inf")
    inf = float("inf")
    cost = np.full((ta + 1, tb + 1), inf, dtype=np.float64)
    cost[0, 0] = 0.0
    # Pairwise distance is L2 per row pair — vectorize along j inside the loop.
    for i in range(1, ta + 1):
        j_start = max(1, i - band)
        j_end = min(tb, i + band) + 1
        if j_start >= j_end:
            continue
        # L2 of a[i-1] against b[j_start-1 : j_end-1]
        diff = b[j_start - 1: j_end - 1] - a[i - 1][np.newaxis, :]
        local_costs = np.linalg.norm(diff, axis=1)
        for jj, j in enumerate(range(j_start, j_end)):
            prev_min = min(cost[i - 1, j], cost[i, j - 1], cost[i - 1, j - 1])
            cost[i, j] = float(local_costs[jj]) + prev_min
    total = cost[ta, tb]
    if total == inf:
        # No valid path inside the band — return a large but finite
        # number so the caller's threshold check still works.
        return 1e6
    # Normalize by the path length (= ta + tb on the optimal warped
    # path's upper bound). Average per-frame cost makes the threshold
    # comparable across templates of different length.
    return float(total) / float(ta + tb)


def build_template_from_takes(
    name: str,
    takes: Sequence,
    key_point_indices: Sequence[int],
    *,
    resampled_length: int = RESAMPLED_FRAME_COUNT,
    match_threshold: Optional[float] = None,
) -> DynamicGestureTemplate:
    """Build a runtime template from a set of `DynamicGestureTake` recordings.

    Run this AFTER `select_key_points` has picked the indices. Each
    take's landmarks are resampled to `resampled_length` and projected
    onto the selected key-point indices. The absolute wrist trajectory
    is captured as a parallel channel and the template's overall wrist-
    motion strength is derived from the per-take path lengths.
    """
    sample_trajectories: List[np.ndarray] = []
    wrist_trajectories: List[np.ndarray] = []
    indices = list(int(i) for i in key_point_indices)
    for take in takes:
        resampled = take.resampled(resampled_length)  # (L, 21, 3)
        # Subtract per-frame wrist so the stored template lives in
        # the same wrist-relative space the live classifier sees
        # after normalize_frame. No-op for recorder-produced takes
        # (already normalized); meaningful only for raw / synthetic
        # takes that include whole-hand translation.
        normalized = resampled - resampled[:, 0:1, :]
        sample_trajectories.append(normalized[:, indices, :].astype(np.float32))
        # Absolute (palm-scaled) wrist channel — carries whole-hand
        # translation that the wrist-relative `normalized` discards.
        try:
            wrist_resampled = take.resampled_wrist(resampled_length)
        except Exception:
            wrist_resampled = np.zeros((resampled_length, 3), dtype=np.float32)
        wrist_trajectories.append(wrist_resampled.astype(np.float32))
    strength = _wrist_motion_strength_from_trajectories(wrist_trajectories)
    return DynamicGestureTemplate(
        name=str(name),
        key_point_indices=indices,
        sample_trajectories=sample_trajectories,
        wrist_trajectories=wrist_trajectories,
        wrist_motion_strength=float(strength),
        match_threshold=match_threshold,
    )


def _wrist_motion_strength_from_trajectories(wrists: Sequence[np.ndarray]) -> float:
    """Map the takes' wrist motion to a [0, _WRIST_WEIGHT_MAX] weight.

    For each take, total path length (sum of per-frame step norms) in
    palm units. Median across takes is robust to one outlier (a
    fumbled retake). The result is clamped to _WRIST_WEIGHT_MAX so
    the finger channel never drops below 1 - MAX of influence.

    A still-hand template (fist squeeze, finger wiggle) → ~0.
    A moderate swipe (~1.5 palm units of total path) → ~_WRIST_WEIGHT_MAX.
    """
    if not wrists:
        return 0.0
    lengths: List[float] = []
    for w in wrists:
        if w is None or w.shape[0] < 2:
            continue
        diffs = np.diff(w.astype(np.float32), axis=0)
        step_norms = np.linalg.norm(diffs, axis=1)
        lengths.append(float(step_norms.sum()))
    if not lengths:
        return 0.0
    median_path = float(np.median(np.asarray(lengths, dtype=np.float32)))
    raw = median_path / max(_WRIST_MOTION_REFERENCE_PALM_UNITS, 1e-6)
    return float(min(max(raw, 0.0), _WRIST_WEIGHT_MAX))
