"""Runtime matcher for dynamic custom gestures.

`DynamicGestureClassifier` consumes a stream of frame-by-frame
normalized hand landmarks and fires a `Match` when the user's recent
motion resembles one of the registered gestures.

Two-stage detection so we don't run DTW on every frame:

  1. **Motion gate**. A short trailing window's path length is
     compared to a low/high threshold pair. When energy crosses
     LOW→HIGH we mark a "gesture in progress"; when it crosses
     HIGH→LOW (the user settled) we close out the segment and run
     stage 2 on it.
  2. **DTW match**. The closed segment's key-point trajectories are
     resampled to the canonical 32 frames and compared against every
     stored sample trajectory of every gesture using Sakoe-Chiba-banded
     DTW. The lowest distance is the winning match — fires only if
     it's also below `match_threshold`.

Cooldowns are external to this class (the existing custom-gesture
runner handles per-gesture cooldowns the same way it does for the
static matcher), so a match can be returned every closed segment.
"""
from __future__ import annotations

from collections import deque
from dataclasses import dataclass, field
from typing import Deque, List, Optional, Sequence, Tuple

import numpy as np

from .dynamic_recording import (
    NUM_LANDMARKS,
    RESAMPLED_FRAME_COUNT,
    _resample_landmarks,
    _resample_wrist,
    build_dynamic_features,
    dynamic_feature_dim,
)


# ---------------------------------------------------------------------------
# Tunables. Tied to the normalized coordinate system (wrist at origin,
# palm scale = 1). Numbers below come from running the recordings
# generated by tests/test_dynamic_gesture_key_points.py through the
# classifier in dev — synthetic but representative.

# Frames retained in the sliding window. At 30 fps that's ~3.3 seconds,
# enough to capture any gesture the user could plausibly perform.
_WINDOW_FRAMES = 100

# Trailing window length used to compute motion energy. Short enough
# to be responsive (so the gate flips within ~150 ms of the user
# starting or stopping), long enough to smooth single-frame jitter.
_MOTION_WINDOW_FRAMES = 5

# Energy gate thresholds in normalized-coords-per-frame. Measured
# as the average over the trailing window of the per-frame MAX
# landmark motion (i.e. the fastest-moving landmark on each frame).
# Using max — not mean — is important: a one-finger swipe only moves
# ~3 of 21 landmarks, so a mean would be dominated by the 18 static
# landmarks and miss the gesture entirely.
#
# Reference numbers (synthetic + real MediaPipe testing at 30 fps):
#   * still hand + MediaPipe jitter: per-frame max ~0.008-0.015
#   * one-finger swipe at moderate speed: per-frame max ~0.030-0.050
#   * fast clap: per-frame max ~0.060-0.120
# Hysteresis gap (LOW < HIGH) prevents bouncing between states on
# borderline motion. Gates are tuned so a normal still hand reliably
# falls below LOW and a deliberate gesture clears HIGH within
# 2-3 frames.
_MOTION_GATE_LOW = 0.018    # below this → "settled"
_MOTION_GATE_HIGH = 0.030   # above this → "in progress"

# r45 (opt-in fps-invariant path — HGR_DYNAMIC_FPS_INVARIANT=1).
# The original gates above are calibrated per-FRAME at 30 fps. At
# 15 fps a still hand's jitter per-frame doubles and can trip HIGH;
# at 60 fps the per-frame step halves and slow deliberate gestures
# never clear it. When the env flag is ON we swap in per-SECOND
# equivalents and divide each per-frame step by real dt so gating
# becomes fps-invariant. DEFAULT OFF preserves existing behaviour
# for all users on all fps (per backward-compat critique — off-30-fps
# users have templates calibrated to the old per-frame semantics).
_MOTION_GATE_LOW_PER_SEC = _MOTION_GATE_LOW * 30.0   # ≈ 0.54
_MOTION_GATE_HIGH_PER_SEC = _MOTION_GATE_HIGH * 30.0  # ≈ 0.90
_NOMINAL_FRAME_DT = 1.0 / 30.0
# Duration floor for the fps-invariant close-out: 8 frames @ 30 fps ≈
# 0.267 s. Only consulted when the env flag is ON.
_MIN_SEGMENT_DURATION_S = 0.25

# v1.1.8.2: `_MIN_SEGMENT_FRAMES` deleted along with the segment
# machine. SPRING has no segment concept. The constructor still
# accepts a `min_segment_frames` kwarg for backward-compat with any
# external caller but it is IGNORED.

# DTW band radius (Sakoe-Chiba). 8 frames of slack on a 32-frame
# template handles speed variations up to ±25% from the recorded
# template. Tighter = faster + stricter timing; looser = more
# forgiving but slower.
_DTW_BAND = 8

# Default match threshold. Average per-frame Euclidean distance
# (across key-point feature vectors) below this is considered a
# match. Tightened from 0.30 → 0.18 after real-hand testing showed
# the looser threshold matched almost any open-hand motion.
_DEFAULT_MATCH_THRESHOLD = 0.18

# Reference wrist path length (palm units) used to map a template's
# per-take wrist motion into a [0, 1] strength weight. A take whose
# wrist travels this many palm units in total is treated as "fully
# wrist-driven" (weight clamps near MAX). A take whose wrist barely
# moves yields weight ≈ 0 — the wrist channel then contributes
# nothing and the classifier matches on fingers alone. Tuned so a
# moderate swipe (~1.5 palm units of total path) lands near 1.0.
_WRIST_MOTION_REFERENCE_PALM_UNITS = 1.5

# Cap on the wrist-channel weight so finger features always retain
# at least 1 - MAX influence on the combined distance. Stops a big
# swipe template from matching ANY fast hand path regardless of
# finger pose. 0.7 = wrist dominates (70%) for big-motion templates
# but fingers still keep 30% weight. v1.1.8.2: audit dropped to
# 0.6, reverted after 0/15 field test — the wrist balance is not
# the current bottleneck. Await diagnostic-log evidence before
# tweaking this constant again.
_WRIST_WEIGHT_MAX = 0.7

# v1.1.8.2: the segment-based tunables (_MAX_SEGMENT_SECONDS,
# _SETTLE_DEBOUNCE_FRAMES, _MIN_SEGMENT_*, _TIMEOUT_MIN_*) were
# DELETED. The classifier is now SPRING streaming — no segment concept
# at all. `_TOP2_MARGIN` still gates simultaneous multi-template
# candidates within a single frame.
_TOP2_MARGIN = 0.04

# FPS estimator bounds. Median of trailing dt values, clamped so a
# process stall / hitch can't yank the estimator to 3 fps (which
# would then let ~1-frame gestures pass _min_segment_frames).
_FPS_EST_MIN = 10.0
_FPS_EST_MAX = 60.0
_FPS_EST_WARMUP = 30.0               # assumed fps until we have samples
_FPS_EST_WINDOW = 10                 # median of trailing N dt values

# v1.1.8.2: `_SEGMENT_LOOKBACK_FRAMES` removed. SPRING sees the entire
# stream naturally; no segment stitching. Motion-energy is still
# tracked as an IDLE-SKIP pre-filter (below).
_IDLE_SKIP_FRAMES = 5                # consecutive idle frames before we
                                     # skip the DP update. Reset on any
                                     # frame at or above LOW/3.


@dataclass(frozen=True)
class DynamicGestureTemplate:
    """A registered gesture the classifier knows how to match.

    `sample_trajectories` is a list of N (one per recorded take) of
    shape (resampled_length, num_key_points, 3). Each is the take's
    key-point trajectory after key-point selection has dropped the
    static / inconsistent landmarks. Storing all N takes (rather than
    just a centroid) lets DTW match against the variant the user is
    most closely reproducing on the current attempt.

    `wrist_trajectories` is a parallel list of N (resampled_length, 3)
    arrays — the absolute (palm-scaled) wrist position per frame for
    each take. This is the second DTW channel: DTW on the finger
    features alone can't distinguish a swipe from "hand entered view
    and held still" (both look like a stationary wrist-relative hand),
    so we also DTW the wrist path and combine the distances weighted
    by how much wrist motion the template's takes actually contained.
    `wrist_motion_strength` is computed at build time in [0, 1] from
    the takes' wrist path lengths and capped at _WRIST_WEIGHT_MAX so
    finger features always retain some influence.
    """

    name: str
    key_point_indices: List[int]
    sample_trajectories: List[np.ndarray]
    wrist_trajectories: List[np.ndarray] = field(default_factory=list)
    wrist_motion_strength: float = 0.0
    # Optional per-gesture threshold. None → use classifier default.
    match_threshold: Optional[float] = None
    # v1.1.8.2 SPRING architecture. One (32, F) matrix per take. When
    # None or empty, the runtime falls back to legacy segment-DTW for
    # THIS template (schema_version < 3). Present for freshly-recorded
    # templates. Fed into per-template SpringMatcher for streaming
    # peak-time firing instead of settle-triggered batch DTW.
    sample_features: List[np.ndarray] = field(default_factory=list)
    # v1.1.8.2 (post-audit round 2) INTENT SIGNATURE. Captures "the
    # essential motion" of the recorded gesture in a form that matches
    # the user's mental model: for wave-up, the signature is "all
    # keypoints moved up by ~X palm-units on average, with a direction
    # unit vector pointing UP." Live matching computes the same signal
    # over a sliding window and fires when direction cosine-similarity
    # + magnitude both cross thresholds. Independent from SPRING —
    # runs in parallel; either can fire.
    #
    # Shape:
    #   direction: (3,)  — unit vector, mean displacement direction
    #                       across all keypoints, all takes
    #   magnitude: float — median total displacement (palm units) across
    #                       takes; a live match needs to hit at least
    #                       0.60 of this magnitude
    #   window_seconds: float — how long the sliding window is, based
    #                       on the recorded take duration
    intent_direction: Optional[List[float]] = None
    intent_magnitude: float = 0.0
    intent_window_seconds: float = 0.0


@dataclass(frozen=True)
class Match:
    """Result of a successful classification."""

    gesture_name: str
    distance: float
    matched_sample_index: int      # which of the gesture's N takes was closest
    segment_frame_count: int
    timestamp: float


# ─────────────────────────────────────────────────────────────────────────
# v1.1.8.2 SPRING (Sakurai et al. VLDB 2007) — streaming subsequence
# DTW. Instead of waiting for a segment to close on settle then running
# batch DTW, feed live features one at a time and emit a per-frame cost.
# The cost curve dips to a local minimum at the frame where the stream
# best matches the template, then rises. Fire on the rise (motion peak),
# not on settle.
#
# Firing rule wraps SpringMatcher externally: (a) cost fell below the
# template's threshold at some frame, (b) has now RISEN for 2 frames
# past its low point (confirms it wasn't a fluke), (c) motion-into-pose
# — cost was above 2× threshold at some point within the last N frames
# (blocks fire on a statically-held hand shape resembling the template),
# (d) top-1 vs top-2 margin across templates.

_SPRING_COOLDOWN_SECONDS = 0.5
_SPRING_MOTION_INTO_POSE_FRAMES = 24  # ~800 ms at 30 fps
# v1.1.8.2 (post-audit): DELTA-based motion-into-pose gate. Replaces the
# absolute `cost >= 2 * threshold` ratio because SPRING's per-row L2
# cost is star-padding-capped and rarely reaches 2x threshold on real
# hand data — the previous formulation rejected every candidate.
# `descent = recent_max - min_cost` measures a real cost drop
# (i.e. an actual motion-into-pose event). `min_abs` is a floor on
# `recent_max` so pure-jitter oscillations that dip 0.3 below their own
# noise floor without crossing this level can't fire.
_SPRING_MOTION_INTO_POSE_DELTA = 0.30    # recent_max - min_cost required
_SPRING_MOTION_INTO_POSE_MIN_ABS = 1.20  # AND recent_max floor
_SPRING_RISE_FRAMES = 2                  # confirm cost has risen 2 frames

# v1.1.8.2 (post-audit round 2) INTENT SIGNATURE thresholds. Fire when
# the live sliding-window displacement matches the template's
# direction well enough AND its magnitude reaches enough of the
# recorded amount. These are FRIENDLY defaults chosen to match the
# user's mental model of "did the hand basically move the right way?"
_INTENT_DIRECTION_COS_MIN = 0.75   # ~40° of tolerance
_INTENT_MAGNITUDE_MIN_FRAC = 0.60  # 60% of the recorded magnitude
# Motion-coherence gate — direction of the window's first half must
# agree with direction of the window's second half. Real waves are
# coherent (~0.9-0.99 cosine); random walks average 0.0-0.3. Blocks
# the classic false-positive from ambient hand jitter.
_INTENT_COHERENCE_MIN = 0.60
_INTENT_COOLDOWN_SECONDS = 0.6


# v1.1.8.2 (post-audit) STEP 6: diagnostic logging helpers behind
# HGR_DYNAMIC_DEBUG=1. Emit one line per non-idle frame + one line per
# candidate rejection so a bad shipping build can be grepped from user
# logs without needing to reproduce.

def _dbg_enabled() -> bool:
    try:
        import os as _os_dbg
        return _os_dbg.environ.get("HGR_DYNAMIC_DEBUG") == "1"
    except Exception:
        return False


def _dbg_log(msg: str) -> None:
    try:
        import logging as _lg
        _lg.getLogger("hgr.dynamic").warning("[DYN] %s", msg)
    except Exception:
        pass


class SpringMatcher:
    """Streaming subsequence DTW.

    template_features: (m, F) matrix. Fed one frame at a time via
    step(feature) → (cur_norm, cur_start, is_rising_after_min,
                       min_cost_so_far, min_start, min_at_t).

    * cur_norm — length-normalized cost cost[m,t] / (t - start + m)
      at the current step. Same units as legacy DTW threshold.
    * cur_start — stream frame index at which the current best
      alignment began.
    * is_rising_after_min — True after the cost has been rising for
      `_SPRING_RISE_FRAMES` consecutive steps past its low point (fire
      signal candidate).
    * min_cost_so_far — the local minimum value the cost dipped to
      before the current rise.
    * min_start — start frame at that minimum.
    * min_at_t — stream frame index of the local minimum.

    Complexity: O(m) per step (all-column DP, unbanded — m=32 is
    small enough that band pruning gains ~zero and adds bugs).
    """

    __slots__ = (
        "_m", "_F", "_template", "_cost", "_start", "_t",
        "_prev_norm", "_last_norm",
        "_running_min", "_running_min_start", "_running_min_t",
        "_rising_count",
    )

    def __init__(self, template_features: np.ndarray) -> None:
        tpl = np.asarray(template_features, dtype=np.float32)
        if tpl.ndim != 2:
            raise ValueError(f"template must be 2D (m, F); got {tpl.shape}")
        self._m = int(tpl.shape[0])
        self._F = int(tpl.shape[1])
        self._template = tpl
        # cost[i] = cumulative cost at template row i (0..m) for current
        # column. Row 0 is star-padded (any stream frame can start a
        # match with 0 accumulated cost).
        self._cost = np.full(self._m + 1, np.inf, dtype=np.float32)
        self._cost[0] = 0.0
        self._start = np.zeros(self._m + 1, dtype=np.int32)
        self._t = 0
        self._prev_norm = float("inf")
        self._last_norm = float("inf")
        self._running_min = float("inf")
        self._running_min_start = 0
        self._running_min_t = -1
        self._rising_count = 0

    def step(self, feature: np.ndarray) -> Tuple[float, int, bool, float, int, int]:
        """One frame in, one match candidate out. See class docstring
        for return-tuple semantics.
        """
        prev_cost = self._cost.copy()
        prev_start = self._start.copy()
        # Star padding: new match can start at THIS frame.
        self._cost[0] = 0.0
        self._start[0] = self._t
        # Vectorized local cost against every template row.
        diff = self._template - feature[np.newaxis, :]
        local = np.linalg.norm(diff, axis=1).astype(np.float32)  # (m,)
        # Dynamic programming column update.
        for i in range(1, self._m + 1):
            # Predecessors: (i-1, t-1), (i, t-1), (i-1, t)
            c_diag = prev_cost[i - 1]
            s_diag = prev_start[i - 1]
            c_up = prev_cost[i]
            s_up = prev_start[i]
            c_left = self._cost[i - 1]
            s_left = self._start[i - 1]
            # Pick min predecessor.
            if c_diag <= c_up and c_diag <= c_left:
                p_c, p_s = c_diag, s_diag
            elif c_up <= c_left:
                p_c, p_s = c_up, s_up
            else:
                p_c, p_s = c_left, s_left
            self._cost[i] = local[i - 1] + p_c
            self._start[i] = p_s
        # Emit current match cost. v1.1.8.2: normalize by template
        # length only, so `cur_norm` is the MEAN per-row local L2
        # distance. Same magnitude as the raw feature values, which
        # makes threshold values interpretable ("features differ by
        # 0.3 per row on average = definitely not a match").
        raw = float(self._cost[self._m])
        start = int(self._start[self._m])
        cur_norm = raw / float(max(1, self._m))
        # Track running minimum + rise streak.
        if cur_norm < self._running_min:
            self._running_min = cur_norm
            self._running_min_start = start
            self._running_min_t = self._t
            self._rising_count = 0
        elif cur_norm > self._last_norm:
            self._rising_count += 1
        else:
            self._rising_count = 0
        is_rising_after_min = self._rising_count >= _SPRING_RISE_FRAMES
        self._prev_norm = self._last_norm
        self._last_norm = cur_norm
        self._t += 1
        return (
            cur_norm, start, is_rising_after_min,
            self._running_min, self._running_min_start, self._running_min_t,
        )

    def clear_running_min(self) -> None:
        """Reset the running-min tracker — call after a fire (or after
        a rejected candidate) so the next dip is measured fresh."""
        self._running_min = float("inf")
        self._running_min_start = 0
        self._running_min_t = -1
        self._rising_count = 0
        self._prev_norm = float("inf")
        self._last_norm = float("inf")

    def reset(self) -> None:
        """Full reset. Called on hand loss."""
        self._cost.fill(np.inf)
        self._cost[0] = 0.0
        self._start.fill(0)
        self._t = 0
        self.clear_running_min()


class DynamicGestureClassifier:
    def __init__(
        self,
        templates: Sequence[DynamicGestureTemplate],
        *,
        match_threshold: float = _DEFAULT_MATCH_THRESHOLD,
        window_frames: int = _WINDOW_FRAMES,
        motion_gate_low: float = _MOTION_GATE_LOW,
        motion_gate_high: float = _MOTION_GATE_HIGH,
        min_segment_frames: int = 8,  # v1.1.8.2: IGNORED — SPRING has no segment concept
        dtw_band: int = _DTW_BAND,
    ) -> None:
        self._templates: List[DynamicGestureTemplate] = list(templates)
        self._match_threshold = float(match_threshold)
        # r45: HGR_DYNAMIC_FPS_INVARIANT=1 opts in to per-second gates.
        # DEFAULT OFF — the constructor arg semantics (per-frame) are
        # preserved byte-for-byte for every existing caller.
        try:
            import os as _os
            self._fps_invariant = _os.environ.get("HGR_DYNAMIC_FPS_INVARIANT", "0") == "1"
        except Exception:
            self._fps_invariant = False
        if self._fps_invariant:
            # Scale the per-frame constructor arg to a per-second gate
            # using the 30-fps identity — a caller passing the default
            # 0.018/0.030 pair gets 0.54/0.90 per-second gates so 30-fps
            # trip points are byte-identical.
            self._motion_gate_low = float(motion_gate_low) / _NOMINAL_FRAME_DT
            self._motion_gate_high = float(motion_gate_high) / _NOMINAL_FRAME_DT
        else:
            self._motion_gate_low = float(motion_gate_low)
            self._motion_gate_high = float(motion_gate_high)
        # v1.1.8.2: min_segment_frames constructor arg is accepted but
        # ignored. SPRING evaluates every frame; no segments.
        _ = int(min_segment_frames)
        self._dtw_band = int(dtw_band)
        # Each entry: (timestamp, normalized_landmarks, wrist_palm_scaled_or_None).
        # The wrist-position third element is optional so the existing
        # 2-arg `update(...)` callers continue to work.
        # v1.1.8.2: sliding-window deque for idle-skip pre-filter only.
        # SPRING doesn't need lookback stitching (no segment concept).
        self._frames: Deque[Tuple[float, np.ndarray, Optional[np.ndarray]]] = deque(
            maxlen=int(window_frames)
        )
        self._recent_dts: Deque[float] = deque(maxlen=_FPS_EST_WINDOW)
        self._last_ts: Optional[float] = None
        # v1.1.8.2 idle-skip counter: consecutive idle-frames seen. When
        # >= _IDLE_SKIP_FRAMES, we short-circuit the SPRING DP entirely
        # (no matmul, no column update) — saves ~90% of CPU when the
        # user's hand is at rest. Reset on any non-idle frame.
        self._idle_streak: int = 0

        # v1.1.8.2 SPRING architecture. Every template with
        # sample_features gets one SpringMatcher per take. Templates
        # without features (legacy schema<3) get an empty row; they
        # will not fire — a one-time WARN log tells the user to
        # re-record. HGR_DYNAMIC_LEGACY=1 disables SPRING entirely.
        try:
            import os as _os_sp
            self._spring_disabled = _os_sp.environ.get(
                "HGR_DYNAMIC_LEGACY", ""
            ).strip() in ("1", "true", "TRUE")
        except Exception:
            self._spring_disabled = False
        self._spring_matchers: List[List["SpringMatcher"]] = []
        legacy_names: List[str] = []
        for tpl in self._templates:
            row: List[SpringMatcher] = []
            if not self._spring_disabled:
                for feat in (tpl.sample_features or []):
                    try:
                        row.append(SpringMatcher(np.asarray(feat, dtype=np.float32)))
                    except Exception:
                        continue
            self._spring_matchers.append(row)
            if not row and not self._spring_disabled:
                legacy_names.append(str(tpl.name))
        # v1.1.8.2 one-time WARN for pre-SPRING templates. They CAN
        # still fire via the intent-signature path if the recorder
        # saved the direction/magnitude; only skip the WARN when the
        # template has intent data.
        legacy_no_intent = [
            n for n, tpl in zip(legacy_names, self._templates)
            if tpl.intent_direction is None or tpl.intent_magnitude <= 1e-4
        ]
        if legacy_no_intent and not self._spring_disabled:
            try:
                import logging as _lg
                _lg.getLogger("hgr.dynamic").warning(
                    "%d dynamic gesture(s) have neither SPRING features nor "
                    "an intent signature and will not fire: %s. Please "
                    "re-record via Custom Gestures wizard.",
                    len(legacy_no_intent), ", ".join(legacy_no_intent[:5]),
                )
            except Exception:
                pass
        # v1.1.8.2 (post-audit r2) init-time diagnostic. HGR_DYNAMIC_DEBUG=1
        # now prints exactly which matcher paths each template has —
        # answers "why isn't anything firing" without needing to inspect
        # the registry JSON.
        if _dbg_enabled():
            for tpl, row in zip(self._templates, self._spring_matchers):
                has_spring = len(row) > 0
                has_intent = (
                    tpl.intent_direction is not None
                    and tpl.intent_magnitude > 1e-4
                )
                _dbg_log(
                    f"init tpl={tpl.name!r} spring_takes={len(row)} "
                    f"intent={'YES' if has_intent else 'NO'} "
                    f"intent_mag={tpl.intent_magnitude:.3f} "
                    f"intent_window={tpl.intent_window_seconds:.2f}s "
                    f"intent_frame=WRIST_ABSOLUTE_PALM_SCALED "
                    f"threshold={tpl.match_threshold}"
                )
            if not any(
                (tpl.intent_direction is not None and tpl.intent_magnitude > 1e-4)
                for tpl in self._templates
            ):
                _dbg_log(
                    "WARN: no template has intent-signature data. "
                    "Templates recorded before v1.1.8.2 (post-audit r2) "
                    "must be re-recorded to enable intent matching."
                )
        # Cooldown: after any SPRING fire, blank all matchers for this
        # many seconds so a returning-to-rest motion doesn't re-fire.
        self._spring_cooldown_until: float = 0.0
        # Motion-into-pose tracking: rolling deque of the last N
        # (t_norm) values PER matcher, so we can enforce "cost was above
        # 2x threshold at some point within the last 800 ms" before we
        # allow a fire. Indexed [template_idx][sample_idx] -> deque.
        self._spring_recent_norms: List[List[Deque[float]]] = [
            [
                deque(maxlen=_SPRING_MOTION_INTO_POSE_FRAMES)
                for _ in row
            ]
            for row in self._spring_matchers
        ]

    @property
    def in_progress(self) -> bool:
        """v1.1.8.2: SPRING has no discrete segment state. Kept for
        backward compat with any UI polling this property — always
        False now."""
        return False

    def reset(self) -> None:
        """Drop the sliding window + reset every SpringMatcher. Call
        when entering a state where recent motion is irrelevant
        (mode switch, dialog open, hand lost)."""
        self._frames.clear()
        self._idle_streak = 0
        for row in getattr(self, "_spring_matchers", []):
            for matcher in row:
                try:
                    matcher.reset()
                except Exception:
                    pass
        for row in getattr(self, "_spring_recent_norms", []):
            for buf in row:
                buf.clear()
        self._spring_cooldown_until = 0.0
        self._recent_dts.clear()
        self._last_ts = None

    def _estimated_fps(self) -> float:
        """v1.1.8.1: median of trailing dt values → fps, clamped to a
        [10, 60] band. Warm-starts at 30 fps until we have >= 3
        samples so early frames don't yank the estimator."""
        if len(self._recent_dts) < 3:
            return _FPS_EST_WARMUP
        med_dt = float(np.median(np.asarray(self._recent_dts, dtype=np.float32)))
        if med_dt <= 1e-6:
            return _FPS_EST_WARMUP
        fps = 1.0 / med_dt
        return float(max(_FPS_EST_MIN, min(_FPS_EST_MAX, fps)))

    def update(
        self,
        landmarks_normalized: np.ndarray,
        timestamp: float,
        *,
        wrist_palm_scaled: Optional[np.ndarray] = None,
    ) -> Optional[Match]:
        """Append one normalized-landmark frame.

        `landmarks_normalized` shape (21, 3) — wrist-relative, palm-
        scaled. Returns a Match when a gesture segment just closed
        AND matched a template; None otherwise.

        `wrist_palm_scaled` is the OPTIONAL absolute wrist position
        in palm units (raw_wrist / palm_scale). When provided, the
        classifier uses it to gate out segments where the wrist
        barely moved — the wrist-relative normalization above
        otherwise can't distinguish a real swipe (whole hand
        translates) from "user brought their hand into view and
        held it steady" (wrist also moves but wrist-relative
        landmarks look identical).
        """
        if landmarks_normalized.shape != (NUM_LANDMARKS, 3):
            raise ValueError(
                f"expected (21, 3); got {landmarks_normalized.shape}"
            )
        wrist_entry: Optional[np.ndarray] = None
        if wrist_palm_scaled is not None:
            wrist_entry = np.asarray(wrist_palm_scaled, dtype=np.float32).reshape(-1)
        ts = float(timestamp)
        # v1.1.8.1: feed the fps estimator with the frame-to-frame dt.
        if self._last_ts is not None:
            dt = ts - float(self._last_ts)
            if dt > 1e-6:
                self._recent_dts.append(dt)
        self._last_ts = ts
        self._frames.append(
            (ts, landmarks_normalized.astype(np.float32), wrist_entry)
        )

        # v1.1.8.2: single streaming SPRING path. No segment machine.
        # Idle-skip pre-filter (motion energy < LOW/3 for
        # _IDLE_SKIP_FRAMES consecutive frames) short-circuits the DP
        # to save CPU while the hand is at rest.
        motion = self._recent_motion_energy()
        idle_threshold = self._motion_gate_low / 3.0
        if motion < idle_threshold:
            self._idle_streak += 1
        else:
            self._idle_streak = 0
        if _dbg_enabled():
            cooldown_left = max(0.0, self._spring_cooldown_until - ts)
            _dbg_log(
                f"tick t={ts:.3f} fps~={self._estimated_fps():.1f} "
                f"motion_e={motion:.4f} idle_streak={self._idle_streak} "
                f"n_tpl={len(self._templates)} cooldown_remaining={cooldown_left:.3f}"
            )
        if self._idle_streak >= _IDLE_SKIP_FRAMES:
            return None
        # v1.1.8.2 (post-audit round 2): INTENT SIGNATURE runs FIRST.
        # This matches the user's mental model — "did the hand move in
        # roughly the direction and magnitude the template captured?"
        # Fires reliably even when SPRING's exact-shape matching is
        # too strict. SPRING remains a fallback for cases where the
        # intent signal is weaker.
        intent_match = self._intent_frame_update(ts, landmarks_normalized, wrist_entry)
        if intent_match is not None:
            return intent_match
        return self._spring_frame_update(ts, landmarks_normalized, wrist_entry)

    # ---- internal ----

    def _recent_motion_energy(self) -> float:
        """Per-frame motion magnitude, averaged over the trailing window.

        Two channels considered, MAX taken:
          * Wrist-relative landmark MAX — the fastest-moving landmark
            in palm-scaled wrist-subtracted space. Captures finger
            motion (curl, spread, wiggle, fist squeeze).
          * Absolute wrist step — the wrist's own palm-scaled
            displacement. Captures whole-hand translation (swipe,
            wave) that wrist-relative landmarks erase.

        Taking MAX means EITHER channel can open the gate, so a rigid-
        hand swipe (still fingers + moving wrist) trips it just as
        readily as an in-place fist squeeze (moving fingers + still
        wrist). Using max-across-landmarks (not mean) for the relative
        channel preserves single-finger gestures the same way; the
        wrist channel is single-valued so it's just the step norm.

        Pre-wrist-channel callers (no wrist data in the deque) fall
        back to the relative channel only — same behaviour as before.
        """
        if len(self._frames) < 2:
            return 0.0
        window = list(self._frames)[-_MOTION_WINDOW_FRAMES:]
        if len(window) < 2:
            return 0.0
        total = 0.0
        for prev, current in zip(window[:-1], window[1:]):
            diff = current[1] - prev[1]  # (21, 3) wrist-relative
            step_norms = np.linalg.norm(diff, axis=-1)  # (21,)
            finger_max = float(step_norms.max())
            wrist_step = 0.0
            prev_wrist = prev[2]
            curr_wrist = current[2]
            if prev_wrist is not None and curr_wrist is not None:
                wrist_step = float(np.linalg.norm(curr_wrist - prev_wrist))
            step = max(finger_max, wrist_step)
            # r45: scale by real dt WHEN the fps-invariant flag is on so
            # the summed energy is displacement/second; otherwise emit
            # per-frame displacement exactly as before. Guarded against
            # zero/negative dt (falls back to nominal 30-fps step).
            if self._fps_invariant:
                dt = float(current[0]) - float(prev[0])
                if not (dt > 1e-6):
                    dt = _NOMINAL_FRAME_DT
                total += step / dt
            else:
                total += step
        return total / max(1, (len(window) - 1))

    # v1.1.8.2: `_segment_wrist_resampled` was DELETED — no segment
    # concept exists in the SPRING architecture. Wrist velocities are
    # per-frame features consumed directly by build_dynamic_features.

    # ---- Intent-signature streaming path (v1.1.8.2 post-audit r2) ----

    def _intent_frame_update(
        self,
        timestamp: float,
        landmarks_normalized: np.ndarray,
        wrist_palm_scaled: Optional[np.ndarray],
    ) -> Optional[Match]:
        """Intent-signature matcher. For each template with an intent
        direction stored, compute the sliding-window WRIST displacement
        (absolute wrist position, palm-scaled — same frame the templates
        were built in) from the earliest frame in-window to this frame.
        Fire when direction cosine-similarity + magnitude fraction both
        cross thresholds.

        v1.1.8.2.1: switched from wrist-RELATIVE fingertip displacement
        to the ABSOLUTE wrist trajectory. Under the old form a wave-up
        (whole hand translates up) had wrist pinned at (0,0,0) every
        frame, so end - start collapsed to sub-palm-unit finger jitter
        and never fired. Now the raw wrist path IS the intent signal.
        Coordinate frame: WRIST_ABSOLUTE_PALM_SCALED (image axes).
        """
        if self._spring_disabled:  # HGR_DYNAMIC_LEGACY also disables intent
            return None
        if not self._templates or len(self._frames) < 3:
            return None
        # Cooldown reuses SPRING's — one fire per gesture regardless of
        # which path caught it.
        if timestamp < self._spring_cooldown_until:
            return None
        # Wrist channel required — matches the record-time coord frame.
        if wrist_palm_scaled is None:
            return None
        end_wrist = np.asarray(wrist_palm_scaled, dtype=np.float32).reshape(-1)
        if end_wrist.shape[0] != 3:
            return None
        # Debug tick.
        _dbg = _dbg_enabled()
        best_fire: Optional[Tuple[float, str, int, float, float, float]] = None
        # tuple: (score = cos * (mag / template_mag), name, tpl_idx, cos, mag_frac, distance)
        for tpl_idx, tpl in enumerate(self._templates):
            if tpl.intent_direction is None or tpl.intent_magnitude <= 1e-4:
                continue
            key_indices = list(tpl.key_point_indices)
            if not key_indices:
                continue
            tpl_dir = np.asarray(tpl.intent_direction, dtype=np.float32)
            tpl_mag = float(tpl.intent_magnitude)
            window = float(tpl.intent_window_seconds) or 1.0
            # Find the frame closest to (now - window) in the buffer.
            target_ts = timestamp - window
            frames = list(self._frames)
            start_idx = 0
            for i in range(len(frames) - 1, -1, -1):
                if frames[i][0] <= target_ts:
                    start_idx = i
                    break
            if start_idx == len(frames) - 1:
                continue  # need at least a window's worth of frames
            start_wrist_raw = frames[start_idx][2]
            if start_wrist_raw is None:
                # No wrist channel in the window's start frame — cannot
                # compare against the wrist-absolute template.
                continue
            start_wrist = np.asarray(start_wrist_raw, dtype=np.float32).reshape(-1)
            if start_wrist.shape[0] != 3:
                continue
            live_disp = end_wrist - start_wrist  # (3,)
            live_mag = float(np.linalg.norm(live_disp))
            # Motion-coherence gate: split the window in half, compare
            # first-half wrist direction to second-half wrist direction.
            # Real waves go one way; random jitter averages to nothing
            # coherent. Fail-closed matches the pre-existing design:
            # if we cannot compute coherence, we do NOT gate — same as
            # when only two frames span the window in the old code.
            mid_idx = (start_idx + len(frames) - 1) // 2
            if mid_idx > start_idx and mid_idx < len(frames) - 1:
                mid_wrist_raw = frames[mid_idx][2]
                if mid_wrist_raw is not None:
                    mid_wrist = np.asarray(mid_wrist_raw, dtype=np.float32).reshape(-1)
                    if mid_wrist.shape[0] == 3:
                        d1 = mid_wrist - start_wrist
                        d2 = end_wrist - mid_wrist
                        n1 = float(np.linalg.norm(d1))
                        n2 = float(np.linalg.norm(d2))
                        if n1 > 1e-4 and n2 > 1e-4:
                            coherence = float(np.dot(d1 / n1, d2 / n2))
                            if coherence < _INTENT_COHERENCE_MIN:
                                if _dbg:
                                    _dbg_log(
                                        f"intent-skip incoherent tpl={tpl.name} "
                                        f"coherence={coherence:.3f} "
                                        f"need>={_INTENT_COHERENCE_MIN}"
                                    )
                                continue
            if live_mag < 1e-4:
                if _dbg:
                    _dbg_log(
                        f"intent-skip zero-mag tpl={tpl.name} "
                        f"window={window:.2f}s frames={len(frames) - start_idx}"
                    )
                continue
            live_dir = live_disp / live_mag
            cos_sim = float(np.dot(live_dir, tpl_dir))
            mag_frac = live_mag / max(tpl_mag, 1e-6)
            if _dbg:
                _dbg_log(
                    f"intent tpl={tpl.name} cos={cos_sim:.3f} "
                    f"mag_frac={mag_frac:.3f} live_mag={live_mag:.3f} "
                    f"tpl_mag={tpl_mag:.3f} need_cos>={_INTENT_DIRECTION_COS_MIN} "
                    f"need_mag_frac>={_INTENT_MAGNITUDE_MIN_FRAC}"
                )
            if cos_sim < _INTENT_DIRECTION_COS_MIN:
                continue
            if mag_frac < _INTENT_MAGNITUDE_MIN_FRAC:
                continue
            # Score by direction confidence × magnitude fraction — higher
            # is better. Cap mag_frac at 1.5 so an accidental huge motion
            # doesn't win over a well-matched normal one.
            score = cos_sim * min(mag_frac, 1.5)
            distance = 1.0 - cos_sim  # for ordering with SPRING semantics
            if best_fire is None or score > best_fire[0]:
                best_fire = (
                    float(score), str(tpl.name), int(tpl_idx),
                    float(cos_sim), float(mag_frac), float(distance),
                )
        if best_fire is None:
            return None
        # Fire!
        self._spring_cooldown_until = timestamp + _INTENT_COOLDOWN_SECONDS
        # Also clear SPRING running-mins so it doesn't fire right after.
        for row in self._spring_matchers:
            for m in row:
                m.clear_running_min()
        for row in self._spring_recent_norms:
            for buf in row:
                buf.clear()
        if _dbg:
            _dbg_log(
                f"FIRE-INTENT tpl={best_fire[1]} cos={best_fire[3]:.3f} "
                f"mag_frac={best_fire[4]:.3f} score={best_fire[0]:.3f}"
            )
        return Match(
            gesture_name=best_fire[1],
            distance=best_fire[5],
            matched_sample_index=0,
            segment_frame_count=0,
            timestamp=float(timestamp),
        )

    # ---- SPRING streaming path ----

    def _spring_frame_update(
        self,
        timestamp: float,
        landmarks_normalized: np.ndarray,
        wrist_entry: Optional[np.ndarray],
    ) -> Optional[Match]:
        """v1.1.8.2 streaming SPRING driver. Called every frame.
        Feeds each template's SpringMatchers, then applies the firing
        rule: cost dipped below threshold + has risen 2 frames past
        the low + motion-into-pose was seen recently + top-1/top-2
        margin. Returns Match at motion peak, or None."""
        if self._spring_disabled or not self._spring_matchers:
            return None
        # Cooldown: skip until _spring_cooldown_until (blocks re-fire on
        # returning-to-rest motion after a legit fire).
        if timestamp < self._spring_cooldown_until:
            return None
        # Need at least 2 frames to compute velocity. Bootstrap silently.
        if len(self._frames) < 2:
            return None
        # Build the single-frame feature vector for THIS frame using the
        # same builder templates use. Reuse the trailing wrist entry to
        # compute a live velocity. Callers that don't supply wrist data
        # get zero-velocity wrist features — finger channel still works.
        prev_ts = float(self._frames[-2][0])
        prev_wrist_raw = self._frames[-2][2]
        prev_wrist_np = (
            np.asarray(prev_wrist_raw, dtype=np.float32).reshape(3)
            if prev_wrist_raw is not None else np.zeros(3, dtype=np.float32)
        )
        curr_wrist_np = (
            np.asarray(wrist_entry, dtype=np.float32).reshape(3)
            if wrist_entry is not None else prev_wrist_np
        )
        _lm2 = np.stack([
            self._frames[-2][1].astype(np.float32),
            landmarks_normalized.astype(np.float32),
        ], axis=0)
        _wr2 = np.stack([prev_wrist_np, curr_wrist_np], axis=0)
        _ts2 = np.array([prev_ts, timestamp], dtype=np.float64)

        # v1.1.8.2 (post-audit) STEP 2: per-TEMPLATE candidate
        # aggregation (samples of the same gesture are NOT competitors
        # for the top-1/top-2 margin) + delta-based motion-into-pose
        # gate that measures a real cost descent (`recent_max -
        # min_cost`) rather than an unreachable absolute cost level.
        best_fire: Optional[Tuple[float, str, int, int]] = None
        second_best_norm: float = float("inf")
        _dbg = _dbg_enabled()
        for tpl_idx, tpl in enumerate(self._templates):
            matchers = self._spring_matchers[tpl_idx]
            if not matchers:
                continue
            key_indices = list(tpl.key_point_indices)
            if not key_indices:
                continue
            try:
                feats2 = build_dynamic_features(_lm2, _wr2, _ts2, key_indices)
            except Exception:
                continue
            if feats2.shape[0] < 2:
                continue
            live_feat = feats2[1]
            threshold = (
                tpl.match_threshold
                if tpl.match_threshold is not None
                else self._match_threshold
            )
            # Per-template best across its N samples (aggregation by
            # min, NOT competition — 3 clustered samples of the same
            # gesture were killing the top-1/top-2 gate).
            tpl_best: Optional[Tuple[float, int]] = None
            for sample_idx, matcher in enumerate(matchers):
                if matcher._F != live_feat.shape[0]:
                    continue
                try:
                    cur_norm, cur_start, is_rising, min_cost, min_start, min_at_t = (
                        matcher.step(live_feat)
                    )
                except Exception:
                    continue
                buf = self._spring_recent_norms[tpl_idx][sample_idx]
                buf.append(float(cur_norm))
                # Gate (a): rising streak ≥ _SPRING_RISE_FRAMES (encoded in is_rising)
                if not is_rising:
                    if _dbg:
                        _dbg_log(
                            f"skip is_rising=False tpl={tpl.name} s={sample_idx} "
                            f"cur={cur_norm:.3f} min={min_cost:.3f} thr={threshold:.3f}"
                        )
                    continue
                # Gate (b): running min below template threshold
                if min_cost >= threshold:
                    if _dbg:
                        _dbg_log(
                            f"skip min>=thr tpl={tpl.name} s={sample_idx} "
                            f"min={min_cost:.3f} thr={threshold:.3f}"
                        )
                    continue
                # Gate (c): delta-based motion-into-pose. `recent_max -
                # min_cost` proves a real descent; `recent_max >=
                # min_abs` floor blocks pure-jitter micro-descents.
                recent_max = max(buf) if buf else float(cur_norm)
                descent = recent_max - float(min_cost)
                if (
                    descent < _SPRING_MOTION_INTO_POSE_DELTA
                    or recent_max < _SPRING_MOTION_INTO_POSE_MIN_ABS
                ):
                    if _dbg:
                        _dbg_log(
                            f"skip no-descent tpl={tpl.name} s={sample_idx} "
                            f"recent_max={recent_max:.3f} min={min_cost:.3f} "
                            f"descent={descent:.3f} "
                            f"need_delta>={_SPRING_MOTION_INTO_POSE_DELTA} "
                            f"need_abs>={_SPRING_MOTION_INTO_POSE_MIN_ABS}"
                        )
                    continue
                # Passing candidate → aggregate per-template.
                if tpl_best is None or min_cost < tpl_best[0]:
                    tpl_best = (float(min_cost), int(sample_idx))
            if tpl_best is None:
                continue
            # Global best/second across TEMPLATES only.
            entry = (tpl_best[0], str(tpl.name), tpl_idx, tpl_best[1])
            if best_fire is None or entry[0] < best_fire[0]:
                if best_fire is not None:
                    second_best_norm = min(second_best_norm, best_fire[0])
                best_fire = entry
            elif entry[0] < second_best_norm:
                second_best_norm = entry[0]

        if best_fire is None:
            return None
        # Top-1 vs top-2 margin — only meaningful when we have >= 2
        # DIFFERENT competing templates. Same-gesture sibling samples
        # were aggregated above, so this only fires on real ambiguity.
        if (
            second_best_norm != float("inf")
            and (second_best_norm - best_fire[0]) < _TOP2_MARGIN
        ):
            if _dbg:
                _dbg_log(
                    f"skip top2 winner={best_fire[1]} winner_cost={best_fire[0]:.3f} "
                    f"runner_up={second_best_norm:.3f} margin={second_best_norm - best_fire[0]:.3f}"
                )
            return None
        if _dbg:
            _dbg_log(
                f"FIRE tpl={best_fire[1]} sample={best_fire[3]} min_cost={best_fire[0]:.3f} "
                f"ts={timestamp:.3f} runner_up={second_best_norm if second_best_norm != float('inf') else -1:.3f}"
            )

        # Fire! Blank all matchers for the cooldown window so returning-
        # to-rest motion doesn't retrigger.
        self._spring_cooldown_until = timestamp + _SPRING_COOLDOWN_SECONDS
        for row in self._spring_matchers:
            for m in row:
                m.clear_running_min()
        # Also drain the recent-norm buffers so the next candidate's
        # motion-into-pose gate re-arms cleanly.
        for row in self._spring_recent_norms:
            for buf in row:
                buf.clear()
        min_cost, name, tpl_idx, sample_idx = best_fire
        return Match(
            gesture_name=name,
            distance=float(min_cost),
            matched_sample_index=int(sample_idx),
            segment_frame_count=0,  # SPRING has no discrete segment
            timestamp=float(timestamp),
        )

    # v1.1.8.2: `_close_and_match` was DELETED. All of the segment-DTW
    # close-time matching, timeout quality gate, and per-template
    # scoring lives in the streaming SPRING path above.


# ---------------------------------------------------------------------------
# DTW (kept as a utility — still consumed by tests + registered-legacy
# runtime threshold computation. Not called from the classifier itself
# after the v1.1.8.2 SPRING rewrite.)

def _dtw_distance(a: np.ndarray, b: np.ndarray, *, band: int = _DTW_BAND) -> float:
    """Sakoe-Chiba-banded DTW returning a length-normalized cost.

    `a`, `b` are (T_a, F) and (T_b, F). Cost is the optimal warped
    cumulative L2 distance between paired frames divided by the
    sum of lengths — this normalizes for the two sequences being
    different lengths so the resulting number is comparable across
    different segments.

    The band constrains the warping path to |i - j| <= band, which
    is enough for ±25% speed differences on a 32-frame template
    and cuts the complexity from O(T_a × T_b) to O(T × band).
    """
    if a.shape[1] != b.shape[1]:
        raise ValueError(f"feature dim mismatch: {a.shape[1]} vs {b.shape[1]}")
    ta, tb = a.shape[0], b.shape[0]
    if ta == 0 or tb == 0:
        return float("inf")
    inf = float("inf")
    cost = np.full((ta + 1, tb + 1), inf, dtype=np.float64)
    cost[0, 0] = 0.0
    # Pairwise distance is L2 per row pair — vectorize along j inside the loop.
    for i in range(1, ta + 1):
        j_start = max(1, i - band)
        j_end = min(tb, i + band) + 1
        if j_start >= j_end:
            continue
        # L2 of a[i-1] against b[j_start-1 : j_end-1]
        diff = b[j_start - 1: j_end - 1] - a[i - 1][np.newaxis, :]
        local_costs = np.linalg.norm(diff, axis=1)
        for jj, j in enumerate(range(j_start, j_end)):
            prev_min = min(cost[i - 1, j], cost[i, j - 1], cost[i - 1, j - 1])
            cost[i, j] = float(local_costs[jj]) + prev_min
    total = cost[ta, tb]
    if total == inf:
        # No valid path inside the band — return a large but finite
        # number so the caller's threshold check still works.
        return 1e6
    # Normalize by the path length (= ta + tb on the optimal warped
    # path's upper bound). Average per-frame cost makes the threshold
    # comparable across templates of different length.
    return float(total) / float(ta + tb)


def build_template_from_takes(
    name: str,
    takes: Sequence,
    key_point_indices: Sequence[int],
    *,
    resampled_length: int = RESAMPLED_FRAME_COUNT,
    match_threshold: Optional[float] = None,
) -> DynamicGestureTemplate:
    """Build a runtime template from a set of `DynamicGestureTake` recordings.

    Run this AFTER `select_key_points` has picked the indices. Each
    take's landmarks are resampled to `resampled_length` and projected
    onto the selected key-point indices. The absolute wrist trajectory
    is captured as a parallel channel and the template's overall wrist-
    motion strength is derived from the per-take path lengths.
    """
    sample_trajectories: List[np.ndarray] = []
    wrist_trajectories: List[np.ndarray] = []
    sample_features: List[np.ndarray] = []
    indices = list(int(i) for i in key_point_indices)
    # v1.1.8.2: motion-onset trim was DISABLED here after synthetic
    # tests showed it distorted the template shape enough that live
    # takes no longer aligned (trim removed ~20% of the take, then
    # resampling to 32 frames warped the remaining motion by the
    # inverse ratio). Kept the trim_to_motion helper available on
    # DynamicGestureTake for the recorder to invoke manually on
    # cleanly-recorded real-hand takes if it wants tighter alignment.
    for take in takes:
        resampled = take.resampled(resampled_length)  # (L, 21, 3)
        # Subtract per-frame wrist so the stored template lives in
        # the same wrist-relative space the live classifier sees
        # after normalize_frame. No-op for recorder-produced takes
        # (already normalized); meaningful only for raw / synthetic
        # takes that include whole-hand translation.
        normalized = resampled - resampled[:, 0:1, :]
        sample_trajectories.append(normalized[:, indices, :].astype(np.float32))
        # v1.1.8.1: wrist channel now stored as DISPLACEMENT from the
        # take's first frame (schema=2). Previously stored absolute
        # (palm-scaled) position, which made a swipe recorded at the
        # left edge fail to match the same swipe performed at the
        # right edge purely because of in-frame offset. The live path
        # applies the same subtraction so the semantics match.
        try:
            wrist_resampled = take.resampled_wrist(resampled_length)
        except Exception:
            wrist_resampled = np.zeros((resampled_length, 3), dtype=np.float32)
        wrist_resampled = wrist_resampled.astype(np.float32)
        # Displacement-from-first-frame — path length is invariant, so
        # wrist_motion_strength computed below is unchanged.
        wrist_resampled = wrist_resampled - wrist_resampled[0:1]
        wrist_trajectories.append(wrist_resampled)
        # v1.1.8.2: build SPRING features from the resampled take. Use
        # the take's own timestamps (resampled to match) so velocity dt
        # is real — a template built with dt=1/30 fixed would drift on
        # any take that was recorded at other fps.
        try:
            ts_resampled = take.resampled_timestamps(resampled_length)
            # v1.1.8.2 (post-audit) STEP 5: pass `normalized` (wrist-
            # subtracted landmarks), not `resampled`, so template
            # features match the LIVE feature builder — which sees
            # normalize_frame's output. For recorder-produced takes
            # this is a no-op (already wrist-subtracted). For synthetic
            # / dev-tool takes that carry whole-hand translation this
            # was inflating template position + fingertip-velocity
            # channels by orders of magnitude and made the synthetic
            # regression test blind to real recall problems.
            feats = build_dynamic_features(
                normalized, wrist_resampled, ts_resampled, indices,
            )
            # v1.1.8.2 (post-audit) STEP 4: backfill row-0 velocity with
            # row-1 values so the template's first frame doesn't have a
            # hard-zero velocity block. Live features always come from a
            # 2-frame window so their velocity is REAL — hard-zero on
            # template row 0 was producing a spurious ~0.05-0.30 cost
            # penalty on any warp path touching row 0.
            if feats.shape[0] >= 2:
                # Only the velocity columns need patching. Position
                # columns are frame-0 already correct.
                key_count = len(indices)
                pos_end = 3 * key_count
                feats[0, pos_end:] = feats[1, pos_end:]
            sample_features.append(feats.astype(np.float32))
        except Exception:
            sample_features.append(np.zeros((resampled_length, 1), dtype=np.float32))
    strength = _wrist_motion_strength_from_trajectories(wrist_trajectories)

    # v1.1.8.2.1 (post-audit round 3) — compute INTENT SIGNATURE from
    # the ABSOLUTE wrist trajectory (palm-scaled, raw image axes).
    # The previous round 2 version derived the signature from wrist-
    # RELATIVE key-point displacement, but on real recorded takes the
    # wrist landmark is already at (0, 0, 0) every frame (recorder
    # normalizes), so start→end deltas collapsed to sub-palm-unit
    # finger jitter — direction was random, magnitude near zero, and
    # wave-up recall was ~0.
    #
    # Coordinate frame: WRIST_ABSOLUTE_PALM_SCALED (image axes:
    # +X image-right, +Y image-down, +Z depth), divided by palm scale.
    # Per-take displacement = wrist_palm_scaled[-1] - wrist_palm_scaled[0].
    # Template signature: average direction unit vector + median
    # magnitude + median window duration.
    intent_direction: Optional[List[float]] = None
    intent_magnitude: float = 0.0
    intent_window_seconds: float = 0.0
    try:
        disp_vecs: List[np.ndarray] = []
        magnitudes: List[float] = []
        durations: List[float] = []
        for take in takes:
            wrist_traj = getattr(take, "wrist_palm_scaled", None)
            if wrist_traj is None:
                continue
            wrist_traj = np.asarray(wrist_traj, dtype=np.float32)
            if (
                wrist_traj.ndim != 2
                or wrist_traj.shape[0] < 2
                or wrist_traj.shape[1] != 3
            ):
                continue
            disp = wrist_traj[-1] - wrist_traj[0]  # (3,)
            mag = float(np.linalg.norm(disp))
            if mag < 1e-4:
                continue
            direction = disp / mag
            disp_vecs.append(direction)
            magnitudes.append(mag)
            try:
                durations.append(float(take.timestamps[-1] - take.timestamps[0]))
            except Exception:
                pass
        if disp_vecs:
            # Average direction (renormalized).
            stacked = np.stack(disp_vecs, axis=0)  # (N, 3)
            mean_dir = stacked.mean(axis=0)
            n = float(np.linalg.norm(mean_dir))
            if n > 1e-6:
                intent_direction = (mean_dir / n).tolist()
                intent_magnitude = float(np.median(magnitudes))
                intent_window_seconds = float(np.median(durations)) if durations else 1.0
                # Clamp window between 0.4 and 2.0 seconds
                intent_window_seconds = max(0.4, min(2.0, intent_window_seconds))
    except Exception:
        pass

    # v1.1.8.2: DTW-based pairwise auto-threshold DELETED. SPRING-native
    # pairwise self-scoring below produces the threshold in the same
    # feature/cost space live matching will use.
    effective_threshold = match_threshold

    # v1.1.8.2 SPRING-native auto-threshold. Run SpringMatcher(take_i)
    # over take_j as the stream and record its minimum cost. The
    # pairwise minimum captures how well the takes SPRING-align against
    # each other in the same feature space live matching will use.
    # Formula: 1.4 * median(pairwise_min) + 0.05, clamped [0.18, 0.28].
    # Tighter than the legacy DTW threshold because SPRING's local min
    # is sharper than the batch-DTW average.
    if effective_threshold is None and len(sample_features) >= 2:
        try:
            spring_mins: List[float] = []
            for i in range(len(sample_features)):
                for j in range(len(sample_features)):
                    if i == j:
                        continue
                    matcher = SpringMatcher(sample_features[i])
                    stream = sample_features[j]
                    best = float("inf")
                    for row in stream:
                        cur, _s, _r, mn, _ms, _mt = matcher.step(row)
                        if mn < best:
                            best = mn
                    if best != float("inf"):
                        spring_mins.append(best)
            if spring_mins:
                med = float(np.median(spring_mins))
                # v1.1.8.2 (post-audit): tightened. Formula
                # 1.35 * median + 0.15 (was 1.5 * median + 0.3),
                # clamp [0.6, 2.0] (was [0.5, 2.5]). On simulated real-
                # hand data with jitter, median_pairwise runs ~1.13 →
                # threshold 1.53 (was 2.0 clamped). This puts the
                # threshold BELOW the achievable running_min ceiling so
                # the min < threshold gate can actually be crossed.
                effective_threshold = float(np.clip(med * 1.35 + 0.15, 0.6, 2.0))
                if _dbg_enabled():
                    _dbg_log(
                        f"threshold_auto tpl={name} median_pairwise={med:.3f} "
                        f"threshold={effective_threshold:.3f} "
                        f"n_takes={len(sample_features)} n_pairwise={len(spring_mins)}"
                    )
        except Exception:
            pass

    return DynamicGestureTemplate(
        name=str(name),
        key_point_indices=indices,
        sample_trajectories=sample_trajectories,
        wrist_trajectories=wrist_trajectories,
        wrist_motion_strength=float(strength),
        match_threshold=effective_threshold,
        sample_features=sample_features,
        intent_direction=intent_direction,
        intent_magnitude=intent_magnitude,
        intent_window_seconds=intent_window_seconds,
    )


def _wrist_motion_strength_from_trajectories(wrists: Sequence[np.ndarray]) -> float:
    """Map the takes' wrist motion to a [0, _WRIST_WEIGHT_MAX] weight.

    For each take, total path length (sum of per-frame step norms) in
    palm units. Median across takes is robust to one outlier (a
    fumbled retake). The result is clamped to _WRIST_WEIGHT_MAX so
    the finger channel never drops below 1 - MAX of influence.

    A still-hand template (fist squeeze, finger wiggle) → ~0.
    A moderate swipe (~1.5 palm units of total path) → ~_WRIST_WEIGHT_MAX.
    """
    if not wrists:
        return 0.0
    lengths: List[float] = []
    for w in wrists:
        if w is None or w.shape[0] < 2:
            continue
        diffs = np.diff(w.astype(np.float32), axis=0)
        step_norms = np.linalg.norm(diffs, axis=1)
        lengths.append(float(step_norms.sum()))
    if not lengths:
        return 0.0
    median_path = float(np.median(np.asarray(lengths, dtype=np.float32)))
    raw = median_path / max(_WRIST_MOTION_REFERENCE_PALM_UNITS, 1e-6)
    return float(min(max(raw, 0.0), _WRIST_WEIGHT_MAX))
