# Touchless PyInstaller spec for macOS (Apple Silicon / arm64).
#
# NEW, SEPARATE from builder/windows/hgr_app.spec — the Windows spec is left
# UNTOUCHED. Produces a Touchless.app bundle. Run from the repo root:
#     pyinstaller builder/macos/hgr_app_mac.spec --noconfirm
# (builder/macos/build_mac.sh wraps this with venv + codesign + pkg/notarize.)
#
# Key differences vs the Windows spec (see docs/MACOS_PORT.md):
#   - BUNDLE(...) -> a .app, not a one-folder COLLECT + Inno installer.
#   - target_arch='arm64'; .icns icon; an embedded Info.plist with the TCC
#     usage-description strings (camera/mic/screen-capture/automation).
#   - onnxruntime (CoreML EP), NOT onnxruntime-directml.
#   - EVERY Windows-only hiddenimport (pywin32/comtypes/pycaw/winsdk/win11toast/
#     uiautomation/pyaudiowpatch/win32*) is dropped; pyobjc is added.
#   - ffmpeg + whisper.cpp/llama.cpp Metal binaries are bundled IF present, but
#     their absence does NOT fail the build (unlike Windows, which hard-errors) —
#     the base build must produce a runnable .app before the Metal phase lands.

import os
import shutil
from pathlib import Path
from PyInstaller.utils.hooks import collect_all, collect_submodules

ROOT = Path.cwd()
SRC = ROOT / "src"
ASSETS = ROOT / "assets"
GESTURE_GUIDE = ROOT / "GestureGuide"
WHISPER_BUNDLES = [ROOT / "whisper.cpp", ROOT / "whisper_bundle"]
LLAMA_ROOT = ROOT / "llama.cpp"

# .icns is generated by build_mac.sh from the 1024px PNG via sips/iconutil.
ICNS = ASSETS / "icons" / "touchless_icon.icns"

BUNDLE_ID = os.environ.get("TOUCHLESS_BUNDLE_ID", "com.touchless.app")

datas = []
binaries = []
hiddenimports = []

# --- Qt + MediaPipe (arm64 wheels) ------------------------------------------
for package_name in ("PySide6", "shiboken6", "mediapipe"):
    pkg_datas, pkg_binaries, pkg_hiddenimports = collect_all(package_name)
    datas += pkg_datas
    binaries += pkg_binaries
    hiddenimports += pkg_hiddenimports

# QtWebEngine (hidden Chromium page for phone-camera WebRTC). On macOS this
# ships QtWebEngineProcess.app as a nested helper; PySide6's hook handles it,
# collect_all reinforces it.
for package_name in ("PySide6.QtWebEngineWidgets", "PySide6.QtWebEngineCore"):
    try:
        pkg_datas, pkg_binaries, pkg_hiddenimports = collect_all(package_name)
        datas += pkg_datas
        binaries += pkg_binaries
        hiddenimports += pkg_hiddenimports
    except Exception:
        pass

# --- onnxruntime (CoreML / CPU). NOT the DirectML wheel. --------------------
try:
    ort_datas, ort_binaries, ort_hidden = collect_all("onnxruntime")
    datas += ort_datas
    binaries += ort_binaries
    hiddenimports += ort_hidden
except Exception:
    pass

# --- App code + cross-platform runtime deps ---------------------------------
hiddenimports += collect_submodules("hgr")
hiddenimports += [
    "cv2",
    "numpy",
    "PIL",
    "psutil",
    "sounddevice",
    "PySide6.QtCore",
    "PySide6.QtGui",
    "PySide6.QtWidgets",
    "PySide6.QtMultimedia",
    "PySide6.QtMultimediaWidgets",
    # macOS platform frameworks (pyobjc) — native_overlay's Darwin branch and
    # the Phase 1+ cursor/screen backends import these lazily.
    "objc",
    "AppKit",
    "Foundation",
    "Quartz",
    # Iris ambient-tools deps that ARE cross-platform (kept ready for when the
    # Iris exclude flips on macOS):
    "mcp",
    "mcp.client",
    "mcp.client.stdio",
    "httplib2",
    "google_auth_httplib2",
    "send2trash",
    "keyring",
]
for _opt in ("mcp",):
    try:
        hiddenimports += collect_submodules(_opt)
    except Exception:
        pass
# pyobjc framework submodules so lazy `from AppKit import X` resolves frozen.
for _fw in ("objc", "AppKit", "Foundation", "Quartz"):
    try:
        hiddenimports += collect_submodules(_fw)
    except Exception:
        pass
hiddenimports = list(dict.fromkeys(hiddenimports))

# --- Static data trees -------------------------------------------------------
for source_path, target_name in (
    (ASSETS, "assets"),
    (GESTURE_GUIDE, "GestureGuide"),
):
    if source_path.exists():
        datas.append((str(source_path), target_name))

# Build-channel marker (mac is always the direct-download 'website' channel —
# there is no Mac App Store auto-update path for the full app). The runtime
# reader hgr.utils.runtime_paths.build_channel() looks for EXACTLY
# 'build_channel.txt' at the bundle root, so the filename must match.
_channel_marker = ROOT / "build" / "build_channel.txt"
_channel_marker.parent.mkdir(parents=True, exist_ok=True)
_channel_marker.write_text("website", encoding="utf-8")
datas.append((str(_channel_marker), "."))

# --- Optional: bundle ffmpeg (arm64) if present (do NOT hard-fail) ----------
_ffmpeg_src = shutil.which("ffmpeg")
if _ffmpeg_src and Path(_ffmpeg_src).exists():
    binaries.append((_ffmpeg_src, "."))
else:
    print("[mac spec] NOTE: ffmpeg not on PATH — bundling without it. The plain "
          "AVFoundation capture path works; the EOS-style subprocess fallback "
          "is Windows-specific anyway.")


def _collect_metal_runtime(roots, subdir_prefix, keep_ext):
    """Bundle Metal-built whisper.cpp / llama.cpp Mach-O binaries IF they exist.

    The macOS Metal builds (builder/macos/_build_whisper_metal.sh,
    _build_llama_metal.sh) emit to <root>/build_metal/bin/. Absent on a base
    build -> returns [] and the voice/Iris-local features degrade to CPU
    (faster-whisper) until the Metal phase lands. No '.exe', no bin/Release.

    NOTE (voice phase): the current runtime finders (voice/whisper_stream.py,
    whisper_refiner.py, voice/llama_server.py, live_api/local_backend.py) only
    search build_cuda/build_vulkan/build_cpu/build and hard-code '.exe' names,
    so anything bundled here is INERT until those finders learn 'build_metal' +
    extensionless Mach-O names. This bundling is intentionally ahead of the
    runtime change; it is a no-op on the base build (Metal is opt-in via
    build_mac.sh --metal).
    """
    collected = []
    for root in roots:
        if not root.exists():
            continue
        models_dir = root / "models"
        if models_dir.exists():
            for model_file in models_dir.glob("ggml-*.bin"):
                collected.append((str(model_file), f"{subdir_prefix}/models"))
        for build_dir_name in ("build_metal", "build"):
            bin_dir = root / build_dir_name / "bin"
            if not bin_dir.exists():
                continue
            for entry in bin_dir.iterdir():
                if entry.is_file() and entry.suffix.lower() in keep_ext:
                    collected.append((str(entry), f"{subdir_prefix}/{build_dir_name}/bin"))
            # Metal needs the shader sidecar next to the binary.
            for shader in bin_dir.glob("*.metal"):
                collected.append((str(shader), f"{subdir_prefix}/{build_dir_name}/bin"))
    return collected


datas += _collect_metal_runtime(WHISPER_BUNDLES, "whisper.cpp", {"", ".bin", ".dylib", ".metal"})
datas += _collect_metal_runtime([LLAMA_ROOT], "llama.cpp", {"", ".dylib", ".metal"})

a = Analysis(
    [str(ROOT / "run_app.py")],
    pathex=[str(ROOT), str(SRC)],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    # Iris (Live API agent) stays excluded from shipping builds on macOS too,
    # for parity with Windows. Flip this when the macOS Iris port (Phase 4) ships.
    excludes=[
        "PyQt5", "PyQt6", "PySide2",
        "hgr.live_api",
        "hgr.app.ui.live_assistant_window",
        # Windows-only libs must never be pulled into the macOS bundle.
        "win32api", "win32con", "win32gui", "win32com", "win32clipboard",
        "win32process", "win32crypt", "pywintypes", "pythoncom", "comtypes",
        "pycaw", "winsdk", "winrt", "uiautomation", "win11toast", "pyaudiowpatch",
    ],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="Touchless",
    console=False,
    target_arch="arm64",
    icon=str(ICNS) if ICNS.exists() else None,
    disable_windowed_traceback=False,
    upx=False,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    name="Touchless",
    upx=False,
)

app = BUNDLE(
    coll,
    name="Touchless.app",
    icon=str(ICNS) if ICNS.exists() else None,
    bundle_identifier=BUNDLE_ID,
    info_plist={
        "CFBundleName": "Touchless",
        "CFBundleDisplayName": "Touchless",
        "CFBundleIdentifier": BUNDLE_ID,
        "CFBundleShortVersionString": os.environ.get("TOUCHLESS_VERSION", "1.0.0"),
        "CFBundleVersion": os.environ.get("TOUCHLESS_BUILD", "1"),
        # Floor is driven by the pinned dependency wheels, not preference: the
        # onnxruntime arm64 wheel targets macOS 14, opencv-contrib 4.11 targets
        # 13. 14.0 keeps the install gate honest. Keep this in sync with
        # installers/macos/distribution.xml (os-version min).
        "LSMinimumSystemVersion": "14.0",
        "NSHighResolutionCapable": True,
        # --- TCC usage strings (REQUIRED — app crashes on first access without
        #     them). Shown verbatim in the system permission prompt. ---
        "NSCameraUsageDescription":
            "Touchless uses the camera to recognize your hand gestures.",
        "NSMicrophoneUsageDescription":
            "Touchless uses the microphone for voice commands and dictation.",
        "NSScreenCaptureUsageDescription":
            "Touchless captures the screen for on-screen actions and the assistant's vision.",
        "NSAppleEventsUsageDescription":
            "Touchless controls other apps (Chrome, Spotify, etc.) to carry out your gestures and commands.",
        "NSSpeechRecognitionUsageDescription":
            "Touchless can use speech recognition as a dictation fallback.",
        # Accessibility / Input Monitoring have no Info.plist key — they are
        # requested at runtime (AXIsProcessTrustedWithOptions) by the first-run
        # onboarding wizard (Phase 5).
    },
)

# Author: Konstantin Markov (macOS port)
